server:
  port: 8443
  servlet:
    context-path: /compute-dashboard-api/v1
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: pkcs12
    key-store-password: ${server.ssl.key-store-password}
    key-alias: tomcat
    enabled: true

okta:
  oauth2:
    issuer: ${okta.oauth2.issuer}
    client-id: ${okta.oauth2.client-id}
    client-secret: ${okta.oauth2.client-secret}

aws:
  accessKeyId: ${aws.accessKeyId}
  secretAccessKey: ${aws.secretAccessKey}